### ISSUE TITLE
New Digimons.

### ISSUE THREAD

**Issue by Brutus123456789** [LordOfDragons/drpgsprviewer#1]
Friend, when will the tool be able to visualize the new digimon? Kdro...

**Comment by LordOfDragons** [comment]
I do not have the game files of this game on my system since a long time. So for the time being I had not planed to take another look at it. Maybe in the future but not right now. I'll keep the issue open for the time being.

**Comment by c100515** [comment]
Hello friend, when can you update the new tool

**Comment by c100515** [comment]
[New.SPR.zip](https://github.com/LordOfDragons/drpgsprviewer/files/6489029/New.SPR.zip)
This is new spr file(Korean version)

**Comment by LordOfDragons** [comment]
Thanks for the files. As mentioned I'm right now really busy so I'll take a look at it once the work load lightened up a bit.

**Comment by c100515** [comment]
> 感谢您的文件。如前所述，我现在很忙，所以一旦工作量减轻一点，我就来看一下。

OK, thanks for your hard work
